# Generated by Django 5.2.8 on 2025-11-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_auther_alter_post_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auther',
        ),
    ]
