# Generated by Django 5.2.8 on 2025-11-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
